[[redirects]]
  from = "/en"
  to = "/en/english.html"
  status = 200

[[redirects]]
  from = "https://playtime-kbsu.netlify.app"
  to = "https://playtimekbsu.ru"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
